### ISSUE TITLE
Add support for Fritz Dect 500 Color Bulb

### ISSUE THREAD

**Issue by kaibuk** [tim-hellhake/fritz-adapter#9] opened 2020-10-14 19:49 UTC
Hi. I wonder if it would be possible to add support for Fritz Dect 500.

I can provide any information required as I have Fritz Box 7590 and Dect 500.

I wonder if we could use a Bulb template from a Han Fun availalbe bulb.

Kind Regards 
Kriss.

**Comment by tim-hellhake** [comment] 2020-10-14 20:16
Hi, @kaibuk I'll see what I can do.
Can you please provide me the log after restarting the adapter?
You can find them at `http://[gateway]:8080/settings/developer` under `View Internal Logs`.

**Comment by kaibuk** [comment] 2020-10-15 17:11
Hello @tim-hellhake 

Attached is the log file. 
[log.txt](https://github.com/tim-hellhake/fritz-adapter/files/5386642/log.txt)

**Comment by tim-hellhake** [comment] 2020-10-15 21:45
I prepared a new release which should support color bulbs.
As soon as the PR is merged, it will be available.
I'm curious if everything works.

**Comment by kaibuk** [comment] 2020-10-16 16:13
Hi Tim. 

I will do some testing and let you know. At the moment I can see that it recognized the devices. 
From the web portal I could switch them on and off and change the colors but will need a bit more time to test it proper. For some reason I had issue to control them from the Mobile Browser, but will let you know. So far it looks good and thank you for a quick reaction on that.

If you want to make you addon even more up to date you can check if you want to add DECT440. Its in my original log. i have that device also so can test but tha tmight require a bit more work.

I will do some testing and will come back to you asap.

**Comment by kaibuk** [comment] 2020-10-19 15:34
Hi Tim.

So I tested the lamps now and here is my Feedback.

In general through the IOT tool if I switch on/off the lamps, change the color or brigtness it does work. The response times are not so bad

Issues:
The noticable issue I found is that it doesn't recognise the latest status the lamp is in. I have a Dect 440 which I use to cotrol the bulbs without a smarthone. So when I switch on the the bud using the Dect 440 or the Fritz Smart Device the Mozilla IOT does not update the status.

Imrpvements:
So what would be good to have it she same color pallet available in the Smart Fritz device. I can provide for that all the RGB codes the app has.

OrI tries to install the addon as a test device to update the colors however it didn't work for me so I wonder if you can tll how i could install the addon so I cna do chagnges and help out.

**Comment by tim-hellhake** [comment] 2020-10-19 15:52
> If you want to make you addon even more up to date you can check if you want to add DECT440

Can you please open another issue for this?

> switch on/off the lamps, change the color or brigtness it does work

Nice!

> it doesn't recognise the latest status the lamp is in

The problem is I didn't find a way to get the current state from the underlying library.
I'll check the official fritz docs if there is a way to fetch the current state.

> So what would be good to have it she same color pallet available in the Smart Fritz device. I can provide for that all the RGB codes the app has.

Can you attach a screenshot of the color controls to the issue?
Are the colors wrong, or is the saturation level missing?
The library I'm using only allows the values I used in the select box.
See https://www.npmjs.com/package/fritzapi#fritzdect-500-and-telekom-bulb-functions _Note 1_.
The saturation level and the color temperature are on my to-do list.

**Comment by kaibuk** [comment] 2020-10-21 18:26
```
` ```
   If you want to make you addon even more up to date you can check if you want to add DECT440`

Can you please open another issue for this?
```

Will do

```


```
    it doesn't recognise the latest status the lamp is in

The problem is I didn't find a way to get the current state from the underlying library.
I'll check the official fritz docs if there is a way to fetch the current state.
```
I can open for that also a different incident as it would bq quie importantto make it working with orher devices. the Smart Fritz app does recogize the status when i change it using Mozilla IOT so depends form the documantation there is definetely adevice status feature

```
Can you attach a screenshot of the color controls to the issue?
Are the colors wrong, or is the saturation level missing?
The library I'm using only allows the values I used in the select box.
See https://www.npmjs.com/package/fritzapi#fritzdect-500-and-telekom-bulb-functions Note 1.
The saturation level and the color temperature are on my to-do list.


so with the colors i actually meant the the Color temperatures. So Note 2 from the link. Its would be great to have but I thing recognizing the Bulb status would be more important as people can have Dect 400, Dect 440 or other Hav Fun switched where they control the Bulbs.
```

Let me know if you want me open a new Call for the Status recognition issue.

**Comment by tim-hellhake** [comment] 2020-10-25 20:20
> so with the colors i actually meant the the Color temperatures.

I see :smile:
I already added this in the meantime: https://github.com/WebThingsIO/addon-list/pull/1116.
So with the update `1.4.0` you should be able to control it.

Update `2.0.0` brings more colors.
I'm now using the fritz API to retrieve the supported `hue`/`sat` combinations.
There should 3 variations of each color.

> I thing recognizing the Bulb status would be more important as people can have Dect 400, Dect 440 or other Hav Fun switched where they control the Bulbs

That's the next thing I'm working on.
The current update already some of the work that is necessary for that.

Can we close this issue now or do I miss something?

**Comment by kaibuk** [comment] 2020-10-27 20:02
Let close that ticket for nwo and i will open a new one after testing. Thank you.

**Comment by tim-hellhake** [comment] 2020-10-27 20:03
You are welcome :)

**Closed as completed** 2020-10-27 20:03 UTC
